- name: Install mongodb_schema
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/momgodb.repo

- name: Install mongodb_schema
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: latest

- name: Loading Schema
  ansible.builtin.shell: mongo --host mongodb-dev.sadguru.shop </app/schema/catalogue.js