- name: Configuring catalogue service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Enabling and restarting catalogue Server
  ansible.builtin.systemd:
    state: restarted
    name: catalogue
    enabled: true
    daemon_reload: true